spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false

server.error.include-message=never
server.error.include-stacktrace=never
pulsetrack.admin.password-hash=${PULSETRACK_ADMIN_PASSWORD_HASH}